### ISSUE TITLE
Create Home Page

### ISSUE THREAD

**Issue by LukeRykta** [LukeRykta/Music-Insights#10]
We need to remove the React default page that is displaying and create our own. Eventually we may use the App.js file (which contains the React default page) to route between pages so keep that there for now. 

- [x] create a new .js file in the frontend/src directory 
- [x] give it a div with some plain text to serve as our "home" page. 
- [x] modify frontend/src/index.js to point to _newPageClassName_ instead of _App_ in order to test it.
- [x] commit new file and push it to your issue branch
- [x] submit pull request

**Comment by antomuangigitau** [comment]
Hello,could you assign this to me
