### ISSUE TITLE
Basic Chart Implementation

### ISSUE THREAD

**Issue by LukeRykta** [LukeRykta/Music-Insights#31]
We need to get a basic chart to display on the chart page. It doesn't have to scale or fit perfectly on the page yet, we only need a rudimentary implementation of a chart.js line graph. 

- [x] Navigate to the frontend directory
- [x] Use terminal to install chart.js (in frontend)
- [x] Copy the basic line graph .js code from the chart.js example into chart page
- [x] Modify as needed
- [x] Run the code using npm configuration (if not setup, see wiki) to test if it displays as expected
- [x] Experiment with local variables to change plotted values
- [x] Push to issue branch
- [x] Pull request

**Comment by Brandon-Price** [comment]
I can't get it to work I tried multiple different ways and methods and I can't get it to work. The screen goes white and that's it and I don't know how to fix it. When every you remove the Chart.js register and importing Chart.js it can fix the site, but when initially loading the site it'll just be white.

![image](https://user-images.githubusercontent.com/90214909/196018273-cfa6890a-cb02-4e30-8b95-10d015a2290d.png)
